import { jsPDF } from "jspdf";

const PrintButtonPdf = ({ subscription, plan, label = "Download as PDF" }) => {
  const generatePdf = () => {
    if (!subscription || !plan) {
      alert("Missing subscription details.");
      return;
    }

    const doc = new jsPDF();

    // Title
    doc.setFontSize(18);
    doc.text("FinalHealth Subscription Summary", 14, 20);

    // Line separator
    doc.setLineWidth(0.5);
    doc.line(14, 25, 196, 25);

    doc.setFontSize(12);

    // Subscription Details
    const price = Number(plan.price);
    const details = [
      { label: "Plan Name", value: plan.planName },
      { label: "Plan Type", value: plan.planType },
      { label: "Price", value: `₱${price}` },
      { label: "Max Users", value: plan.maxNumberUsers },
      { label: "Max Patients", value: plan.maxNumberPatient },
      { label: "Description", value: plan.description },
      { label: "Subscription ID", value: subscription.subscriptionId },
      { label: "Status", value: subscription.status },
      {
        label: "Auto Renew",
        value: subscription.autoRenew ? "Enabled" : "Disabled",
      },
      { label: "Start Date", value: subscription.startDate },
      { label: "End Date", value: subscription.endDate },
      {
        label: "Created At",
        value: new Date(subscription.createdAt).toLocaleString(),
      },
    ];

    let y = 35;
    details.forEach((item) => {
      doc.setFont("Helvetica", "bold");
      doc.text(`${item.label}:`, 14, y);
      doc.setFont("Helvetica", "normal");
      doc.text(String(item.value), 60, y);
      y += 8;
    });

    // Footer
    doc.setFontSize(10);
    doc.text("Generated by FinalHealth", 14, 285);

    // Save the PDF
    doc.save("subscription-summary.pdf");
  };

  return (
    <button
      type="button"
      onClick={generatePdf}
      className="w-full px-6 py-3 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition duration-200 font-semibold"
    >
      {label}
    </button>
  );
};

export default PrintButtonPdf;
